version: "3"
name: springboot-mysql-compose

services:
  app:
    container_name: khalid-springboot
    build:
      context: .
      dockerfile: ./Dockerfile2
    image: khaliddinh/springboot
    ports:
      - "8082:8082"
    # restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://khalid-java-mysql:3306/db_example
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - java-app

  mysql:
    container_name: khalid-java-mysql
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db_example
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - khalid-java-mysql-data:/var/lib/mysql
    networks:
      - java-app

volumes:
  khalid-java-mysql-data:
networks:
  java-app:
    name: java-app